export const RESET_TRANSACTION_FORM = 'RESET_TRANSACTION_FORM';
export const APPEND_TRANSACTION_FORM = 'APPEND_TRANSACTION_FORM';

export const VALIDATE_TRANSACTION_REQUEST = 'VALIDATE_TRANSACTION_REQUEST';
export const VALIDATE_TRANSACTION_SUCCESS = 'VALIDATE_TRANSACTION_SUCCESS';
export const VALIDATE_TRANSACTION_FAILURE = 'VALIDATE_TRANSACTION_FAILURE';

export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
export const APPEND_LOGIN_FORM = 'APPEND_LOGIN_FORM';

export const VALIDATE_LOGIN_REQUEST = 'VALIDATE_LOGIN_REQUEST';
export const VALIDATE_LOGIN_SUCCESS = 'VALIDATE_LOGIN_SUCCESS';
export const VALIDATE_LOGIN_FAILURE = 'VALIDATE_LOGIN_FAILURE';

export const SET_EDIT_MODE_PROFILE = 'SET_EDIT_MODE_PROFILE';

export const APPEND_PROFILE_FORM = 'APPEND_PROFILE_FORM';

export const VALIDATE_PROFILE_REQUEST = 'VALIDATE_PROFILE_REQUEST';
export const VALIDATE_PROFILE_SUCCESS = 'VALIDATE_PROFILE_SUCCESS';
export const VALIDATE_PROFILE_FAILURE = 'VALIDATE_PROFILE_FAILURE';

export const VALIDATE_DONATION_PROFILE_REQUEST = 'VALIDATE_DONATION_PROFILE_REQUEST';
export const VALIDATE_DONATION_PROFILE_SUCCESS = 'VALIDATE_DONATION_PROFILE_SUCCESS';
export const VALIDATE_DONATION_PROFILE_FAILURE = 'VALIDATE_DONATION_PROFILE_FAILURE';

export const APPEND_DONATION_FORM = 'APPEND_DONATION_FORM';

export const APPEND_GROUP_SETTINGS_FORM = 'APPEND_GROUP_SETTINGS_FORM';

export const VALIDATE_GROUP_SETTING_ATTRIBUTE_CHANGE_REQUEST = 'VALIDATE_GROUP_SETTING_ATTRIBUTE_CHANGE_REQUEST';
export const VALIDATE_GROUP_SETTING_ATTRIBUTE_CHANGE_SUCCESS = 'VALIDATE_GROUP_SETTING_ATTRIBUTE_CHANGE_SUCCESS';
export const VALIDATE_GROUP_SETTING_ATTRIBUTE_CHANGE_FAILURE = 'VALIDATE_GROUP_SETTING_ATTRIBUTE_CHANGE_FAILURE';

export const VALIDATE_SCHEMA_REQUEST = 'VALIDATE_SCHEMA_REQUEST';
export const VALIDATE_SCHEMA_SUCCESS = 'VALIDATE_SCHEMA_SUCCESS';
export const VALIDATE_SCHEMA_FAILURE = 'VALIDATE_SCHEMA_FAILURE';
