export const GROUP_REQUEST = 'GROUP_REQUEST';
export const GROUP_SUCCESS = 'GROUP_SUCCESS';
export const GROUP_FAILURE = 'GROUP_FAILURE';

export const DONATE_GROUP_REQUEST = 'DONATE_GROUP_REQUEST';
export const DONATE_GROUP_SUCCESS = 'DONATE_GROUP_SUCCESS';
export const DONATE_GROUP_FAILURE = 'DONATE_GROUP_FAILURE';

