export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const DECODE_JWT_SUCCESS = 'DECODE_JWT_SUCCESS';
export const DECODE_JWT_FAILURE = 'DECODE_JWT_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SHOW_POPOVERMENU = 'SHOW_POPOVERMENU';

export const DECODE_JWT_EMPTY = 'DECODE_JWT_EMPTY';
