export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USER_FROM_STATE = 'FETCH_USER_FROM_STATE';

export const USER_GROUPS_REQUEST = 'USER_GROUPS_REQUEST';
export const USER_GROUPS_SUCCESS = 'USER_GROUPS_SUCCESS';
export const USER_GROUPS_FAILURE = 'USER_GROUPS_FAILURE';

export const USER_TRANSACTIONS_REQUEST = 'USER_TRANSACTIONS_REQUEST';
export const USER_TRANSACTIONS_SUCCESS = 'USER_TRANSACTIONS_SUCCESS';
export const USER_TRANSACTIONS_FAILURE = 'USER_TRANSACTIONS_FAILURE';

export const GET_APPROVAL_KEY_FOR_USER_REQUEST= 'GET_APPROVAL_KEY_FOR_USER_REQUEST';
export const GET_APPROVAL_KEY_FOR_USER_SUCCESS = 'GET_APPROVAL_KEY_FOR_USER_SUCCESS';
export const GET_APPROVAL_KEY_FOR_USER_FAILURE = 'GET_APPROVAL_KEY_FOR_USER_FAILURE';

export const CONFIRM_APPROVAL_KEY_REQUEST = 'CONFIRM_APPROVAL_KEY_REQUEST';
export const CONFIRM_APPROVAL_KEY_SUCCESS = 'CONFIRM_APPROVAL_KEY_SUCCESS';
export const CONFIRM_APPROVAL_KEY_FAILURE = 'CONFIRM_APPROVAL_KEY_FAILURE';

export const UPDATE_PAYPAL_EMAIL_REQUEST = 'UPDATE_PAYPAL_EMAIL_REQUEST';
export const UPDATE_PAYPAL_EMAIL_SUCCESS = 'UPDATE_PAYPAL_EMAIL_SUCCESS';
export const UPDATE_PAYPAL_EMAIL_FAILURE = 'UPDATE_PAYPAL_EMAIL_FAILURE';

export const UPDATE_AVATAR_REQUEST = 'UPDATE_AVATAR_REQUEST';
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_FAILURE = 'UPDATE_AVATAR_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const USER_CARDS_REQUEST = 'USER_CARDS_REQUEST';
export const USER_CARDS_SUCCESS = 'USER_CARDS_SUCCESS';
export const USER_CARDS_FAILURE = 'USER_CARDS_FAILURE';

export const GET_PREAPPROVAL_DETAILS_REQUEST = 'GET_PREAPPROVAL_DETAILS_REQUEST';
export const GET_PREAPPROVAL_DETAILS_SUCCESS = 'GET_PREAPPROVAL_DETAILS_SUCCESS';
export const GET_PREAPPROVAL_DETAILS_FAILURE = 'GET_PREAPPROVAL_DETAILS_FAILURE';

export const FETCH_USERS_BY_GROUP_REQUEST = 'FETCH_USERS_BY_GROUP_REQUEST';
export const FETCH_USERS_BY_GROUP_SUCCESS = 'FETCH_USERS_BY_GROUP_SUCCESS';
export const FETCH_USERS_BY_GROUP_FAILURE = 'FETCH_USERS_BY_GROUP_FAILURE';

export const SHOW_ADDITIONAL_USER_INFO_FORM = 'SHOW_ADDITIONAL_USER_INFO_FORM';
export const HIDE_ADDITIONAL_USER_INFO_FORM = 'HIDE_ADDITIONAL_USER_INFO_FORM';

export const AUTHORIZE_STRIPE_REQUEST = 'AUTHORIZE_STRIPE_REQUEST';
export const AUTHORIZE_STRIPE_SUCCESS = 'AUTHORIZE_STRIPE_SUCCESS';
export const AUTHORIZE_STRIPE_FAILURE = 'AUTHORIZE_STRIPE_FAILURE';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

export const SEND_RESET_PASSWORD_LINK_REQUEST = 'SEND_RESET_PASSWORD_LINK_REQUEST';
export const SEND_RESET_PASSWORD_LINK_SUCCESS = 'SEND_RESET_PASSWORD_LINK_SUCCESS';
export const SEND_RESET_PASSWORD_LINK_FAILURE = 'SEND_RESET_PASSWORD_LINK_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';