export const COLLECTIVE_REQUEST = 'COLLECTIVE_REQUEST';
export const COLLECTIVE_SUCCESS = 'COLLECTIVE_SUCCESS';
export const COLLECTIVE_FAILURE = 'COLLECTIVE_FAILURE';

export const UPDATE_COLLECTIVE_REQUEST = 'UPDATE_COLLECTIVE_REQUEST';
export const UPDATE_COLLECTIVE_SUCCESS = 'UPDATE_COLLECTIVE_SUCCESS';
export const UPDATE_COLLECTIVE_FAILURE = 'UPDATE_COLLECTIVE_FAILURE';

export const DONATE_COLLECTIVE_REQUEST = 'DONATE_COLLECTIVE_REQUEST';
export const DONATE_COLLECTIVE_SUCCESS = 'DONATE_COLLECTIVE_SUCCESS';
export const DONATE_COLLECTIVE_FAILURE = 'DONATE_COLLECTIVE_FAILURE';
