export const CONNECTED_ACCOUNTS_REQUEST = 'CONNECTED_ACCOUNTS_REQUEST';
export const CONNECTED_ACCOUNTS_SUCCESS = 'CONNECTED_ACCOUNTS_SUCCESS';
export const CONNECTED_ACCOUNTS_FAILURE = 'CONNECTED_ACCOUNTS_FAILURE';
