export const DONATIONS_REQUEST = 'DONATIONS_REQUEST';
export const DONATIONS_SUCCESS = 'DONATIONS_SUCCESS';
export const DONATIONS_FAILURE = 'DONATIONS_FAILURE';

export const DONATION_REQUEST = 'DONATION_REQUEST';
export const DONATION_SUCCESS = 'DONATION_SUCCESS';
export const DONATION_FAILURE = 'DONATION_FAILURE';
