export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const CREATE_EXPENSE_FAILURE = 'CREATE_EXPENSE_FAILURE';

export const EXPENSES_REQUEST = 'EXPENSES_REQUEST';
export const EXPENSES_SUCCESS = 'EXPENSES_SUCCESS';
export const EXPENSES_FAILURE = 'EXPENSES_FAILURE';

export const EXPENSE_REQUEST = 'EXPENSE_REQUEST';
export const EXPENSE_SUCCESS = 'EXPENSE_SUCCESS';
export const EXPENSE_FAILURE = 'EXPENSE_FAILURE';

export const PENDING_EXPENSES_REQUEST = 'PENDING_EXPENSES_REQUEST';
export const PENDING_EXPENSES_SUCCESS = 'PENDING_EXPENSES_SUCCESS';
export const PENDING_EXPENSES_FAILURE = 'PENDING_EXPENSES_FAILURE';

export const APPROVE_EXPENSE_REQUEST = 'APPROVE_EXPENSE_REQUEST';
export const APPROVE_EXPENSE_SUCCESS = 'APPROVE_EXPENSE_SUCCESS';
export const APPROVE_EXPENSE_FAILURE = 'APPROVE_EXPENSE_FAILURE';

export const REJECT_EXPENSE_REQUEST = 'REJECT_EXPENSE_REQUEST';
export const REJECT_EXPENSE_SUCCESS = 'REJECT_EXPENSE_SUCCESS';
export const REJECT_EXPENSE_FAILURE = 'REJECT_EXPENSE_FAILURE';

export const PAY_EXPENSE_REQUEST = 'PAY_EXPENSE_REQUEST';
export const PAY_EXPENSE_SUCCESS = 'PAY_EXPENSE_SUCCESS';
export const PAY_EXPENSE_FAILURE = 'PAY_EXPENSE_FAILURE';

export const EXPENSE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PAID: 'PAID'
};