export const CREATE_EXPENSE_REQUEST = 'CREATE_EXPENSE_REQUEST';
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS';
export const CREATE_EXPENSE_FAILURE = 'CREATE_EXPENSE_FAILURE';

export const EXPENSES_REQUEST = 'EXPENSES_REQUEST';
export const EXPENSES_SUCCESS = 'EXPENSES_SUCCESS';
export const EXPENSES_FAILURE = 'EXPENSES_FAILURE';

export const EXPENSE_REQUEST = 'EXPENSE_REQUEST';
export const EXPENSE_SUCCESS = 'EXPENSE_SUCCESS';
export const EXPENSE_FAILURE = 'EXPENSE_FAILURE';