export const APPEND_PROFILE_FORM = 'APPEND_PROFILE_FORM';

export const VALIDATE_PROFILE_REQUEST = 'VALIDATE_PROFILE_REQUEST';
export const VALIDATE_PROFILE_SUCCESS = 'VALIDATE_PROFILE_SUCCESS';
export const VALIDATE_PROFILE_FAILURE = 'VALIDATE_PROFILE_FAILURE';

export const APPEND_DONATION_FORM = 'APPEND_DONATION_FORM';

export const VALIDATE_SCHEMA_REQUEST = 'VALIDATE_SCHEMA_REQUEST';
export const VALIDATE_SCHEMA_SUCCESS = 'VALIDATE_SCHEMA_SUCCESS';
export const VALIDATE_SCHEMA_FAILURE = 'VALIDATE_SCHEMA_FAILURE';

export const RESET_TRANSACTION_FORM = 'RESET_TRANSACTION_FORM';
export const APPEND_TRANSACTION_FORM = 'APPEND_TRANSACTION_FORM';

export const VALIDATE_TRANSACTION_REQUEST = 'VALIDATE_TRANSACTION_REQUEST';
export const VALIDATE_TRANSACTION_SUCCESS = 'VALIDATE_TRANSACTION_SUCCESS';
export const VALIDATE_TRANSACTION_FAILURE = 'VALIDATE_TRANSACTION_FAILURE';
