export const APPEND_GITHUB_FORM = 'APPEND_GITHUB_FORM';
export const APPEND_GROUP_FORM = 'APPEND_GROUP_FORM';
export const APPEND_EDIT_GROUP_FORM = 'APPEND_EDIT_GROUP_FORM';
export const CANCEL_EDIT_GROUP_FORM = 'CANCEL_EDIT_GROUP_FORM';

export const APPEND_PROFILE_FORM = 'APPEND_PROFILE_FORM';

export const VALIDATE_PROFILE_REQUEST = 'VALIDATE_PROFILE_REQUEST';
export const VALIDATE_PROFILE_SUCCESS = 'VALIDATE_PROFILE_SUCCESS';
export const VALIDATE_PROFILE_FAILURE = 'VALIDATE_PROFILE_FAILURE';

export const APPEND_DONATION_FORM = 'APPEND_DONATION_FORM';

export const VALIDATE_SCHEMA_REQUEST = 'VALIDATE_SCHEMA_REQUEST';
export const VALIDATE_SCHEMA_SUCCESS = 'VALIDATE_SCHEMA_SUCCESS';
export const VALIDATE_SCHEMA_FAILURE = 'VALIDATE_SCHEMA_FAILURE';

export const RESET_EXPENSE_FORM = 'RESET_EXPENSE_FORM';
export const APPEND_EXPENSE_FORM = 'APPEND_EXPENSE_FORM';

export const VALIDATE_EXPENSE_REQUEST = 'VALIDATE_EXPENSE_REQUEST';
export const VALIDATE_EXPENSE_SUCCESS = 'VALIDATE_EXPENSE_SUCCESS';
export const VALIDATE_EXPENSE_FAILURE = 'VALIDATE_EXPENSE_FAILURE';

export const APPEND_TWITTER_CONFIG_FORM = 'APPEND_TWITTER_CONFIG_FORM';
