export const GROUP_REQUEST = 'GROUP_REQUEST';
export const GROUP_SUCCESS = 'GROUP_SUCCESS';
export const GROUP_FAILURE = 'GROUP_FAILURE';

export const UPDATE_GROUP_REQUEST = 'UPDATE_GROUP_REQUEST';
export const UPDATE_GROUP_SUCCESS = 'UPDATE_GROUP_SUCCESS';
export const UPDATE_GROUP_FAILURE = 'UPDATE_GROUP_FAILURE';

export const UPDATE_GROUP_MEMBERS_REQUEST = 'UPDATE_GROUP_MEMBERS_REQUEST';
export const UPDATE_GROUP_MEMBERS_SUCCESS = 'UPDATE_GROUP_MEMBERS_SUCCESS';
export const UPDATE_GROUP_MEMBERS_FAILURE = 'UPDATE_GROUP_MEMBERS_FAILURE';

export const DONATE_GROUP_REQUEST = 'DONATE_GROUP_REQUEST';
export const DONATE_GROUP_SUCCESS = 'DONATE_GROUP_SUCCESS';
export const DONATE_GROUP_FAILURE = 'DONATE_GROUP_FAILURE';

export const GET_LEADERBOARD_REQUEST = 'GET_LEADERBOARD_REQUEST';
export const GET_LEADERBOARD_SUCCESS = 'GET_LEADERBOARD_SUCCESS';
export const GET_LEADERBOARD_FAILURE = 'GET_LEADERBOARD_FAILURE';

export const CREATE_GROUP_FROM_GITHUB_REPO_REQUEST = 'CREATE_GROUP_FROM_GITHUB_REPO_REQUEST';
export const CREATE_GROUP_FROM_GITHUB_REPO_SUCCESS = 'CREATE_GROUP_FROM_GITHUB_REPO_SUCCESS';
export const CREATE_GROUP_FROM_GITHUB_REPO_FAILURE = 'CREATE_GROUP_FROM_GITHUB_REPO_FAILURE';

export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE = 'CREATE_GROUP_FAILURE';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const GROUP_TAGS_REQUEST = 'GROUP_TAGS_REQUEST';
export const GROUP_TAGS_SUCCESS = 'GROUP_TAGS_SUCCESS';
export const GROUP_TAGS_FAILURE = 'GROUP_TAGS_FAILURE';

export const GROUP_TIER_LIST_REQUEST = 'GROUP_TIER_LIST_REQUEST';
export const GROUP_TIER_LIST_SUCCESS = 'GROUP_TIER_LIST_SUCCESS';
export const GROUP_TIER_LIST_FAILURE = 'GROUP_TIER_LIST_FAILURE';
