export const DECODE_JWT_SUCCESS = 'DECODE_JWT_SUCCESS';
export const DECODE_JWT_FAILURE = 'DECODE_JWT_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const DECODE_JWT_EMPTY = 'DECODE_JWT_EMPTY';

export const HYDRATE = 'HYDRATE';

export const STORE_TOKEN_SUCCESS = 'STORE_TOKEN_SUCCESS';
export const STORE_TOKEN_FAILURE = 'STORE_TOKEN_FAILURE';
