export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USER_FROM_STATE = 'FETCH_USER_FROM_STATE';

export const USER_GROUPS_REQUEST = 'USER_GROUPS_REQUEST';
export const USER_GROUPS_SUCCESS = 'USER_GROUPS_SUCCESS';
export const USER_GROUPS_FAILURE = 'USER_GROUPS_FAILURE';

export const USER_TRANSACTIONS_REQUEST = 'USER_TRANSACTIONS_REQUEST';
export const USER_TRANSACTIONS_SUCCESS = 'USER_TRANSACTIONS_SUCCESS';
export const USER_TRANSACTIONS_FAILURE = 'USER_TRANSACTIONS_FAILURE';

export const GET_APPROVAL_KEY_FOR_USER_REQUEST= 'GET_APPROVAL_KEY_FOR_USER_REQUEST';
export const GET_APPROVAL_KEY_FOR_USER_SUCCESS = 'GET_APPROVAL_KEY_FOR_USER_SUCCESS';
export const GET_APPROVAL_KEY_FOR_USER_FAILURE = 'GET_APPROVAL_KEY_FOR_USER_FAILURE';

export const CONFIRM_APPROVAL_KEY_REQUEST = 'CONFIRM_APPROVAL_KEY_REQUEST';
export const CONFIRM_APPROVAL_KEY_SUCCESS = 'CONFIRM_APPROVAL_KEY_SUCCESS';
export const CONFIRM_APPROVAL_KEY_FAILURE = 'CONFIRM_APPROVAL_KEY_FAILURE';

export const UPDATE_PAYPAL_EMAIL_REQUEST = 'UPDATE_PAYPAL_EMAIL_REQUEST';
export const UPDATE_PAYPAL_EMAIL_SUCCESS = 'UPDATE_PAYPAL_EMAIL_SUCCESS';
export const UPDATE_PAYPAL_EMAIL_FAILURE = 'UPDATE_PAYPAL_EMAIL_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const FETCH_USERS_BY_GROUP_REQUEST = 'FETCH_USERS_BY_GROUP_REQUEST';
export const FETCH_USERS_BY_GROUP_SUCCESS = 'FETCH_USERS_BY_GROUP_SUCCESS';
export const FETCH_USERS_BY_GROUP_FAILURE = 'FETCH_USERS_BY_GROUP_FAILURE';

export const REFRESH_SUBSCRIPTIONS_TOKEN_REQUEST = 'REFRESH_SUBSCRIPTIONS_TOKEN_REQUEST';
export const REFRESH_SUBSCRIPTIONS_TOKEN_SUCCESS = 'REFRESH_SUBSCRIPTIONS_TOKEN_SUCCESS';
export const REFRESH_SUBSCRIPTIONS_TOKEN_FAILURE = 'REFRESH_SUBSCRIPTIONS_TOKEN_FAILURE';

export const SEND_NEW_SUBSCRIPTIONS_TOKEN_REQUEST = 'SEND_NEW_SUBSCRIPTIONS_TOKEN_REQUEST';
export const SEND_NEW_SUBSCRIPTIONS_TOKEN_SUCCESS = 'SEND_NEW_SUBSCRIPTIONS_TOKEN_SUCCESS';
export const SEND_NEW_SUBSCRIPTIONS_TOKEN_FAILURE = 'SEND_NEW_SUBSCRIPTIONS_TOKEN_FAILURE';
